### ISSUE TITLE
Forge does not work

### ISSUE THREAD

**Issue by MrScautHD** [DemonWav/MinecraftDevIntelliJ#1048]
Hi i have tryed to make a 1.17.1 workspace with the plugin but its gives always Build errors or Gradle Errors... i hope you can fix that :D (and pls support the offical mappings and java 16)

Please include the following information in all bug reports:

* Minecraft Development for IntelliJ plugin version (newst)
* IntelliJ version (newst)
* Operating System (this has come up enough times to be worth noting) (Windwos 10)
* (optional) Target platform, if relevant
  * Forge

Always include a stack trace if there is one. Otherwise, the more information you can provide in terms of how to reproduce the problem, the more likely it'll be fixed. If there is something specific about your project, a link to the GitHub project can be very helpful.

**Comment by SirEndii** [comment]
Don't use "newst" or "latest" as version. You should always state the version that you are actually using. Maybe you use not the latest beta version of Intellij, so it's not "newest".

And please change the title to "Forge does not work". "Forge works not" isn't the best english.

>  Build errors or Gradle Errors

We need more information about it. Send logs. 
But this plugin shouldn't be the issue.

**Comment by RedNesto** [comment]
Fixed in 60919926d87c849bf061c78774393cadc007c824 that should be included in the next nightly build (255 if nothing goes wrong.)

Note the wizard doesn't know about mappings channels other than stable and snapshot. Mappings version is ignored for Forge 1.17+ until a solution is implemented, so don't worry about the error message in the Forge step.

And please provide a real versions next time, relative versions are really unhelpful when asking for help (as Seniorendi said).

**Comment by MrScautHD** [comment]
ok sry, and thx for fixing it!
