### ISSUE TITLE
Package naming conventions wrong

### ISSUE THREAD

**Issue by Redrield** [DemonWav/MinecraftDevIntelliJ#16]
So when you create a project with this, you capitalize the package names. This is something that really should be changed, as I don't like having to go and make them all lowercase. Also when I type a name in CamelCase, you remove any capitals after the first one. Can you just leave the name as is (except for package names) :)

**Comment by DemonWav** [comment]
I do not understand what you mean by this, there is no capitalization of the package names at all, except for the main class name, which should be capitalized. It uses what you give it. You'll have to provide an example.

**Comment by Redrield** [comment]
See [https://gyazo.com/8816d224b73d8c6d56ee91c52fb80feb](This example). The package keeps the CamelCase of the name I give the plugin. The package name should have #toLowerCase() called on it. Also, I changed it in this example but as I said, I named the plugin TestPlugin, but the main class was named Testplugin, Please don't remove capitals that aren't the first letter

**Comment by DemonWav** [comment]
I can see what you mean, though [naming standards](https://maven.apache.org/guides/mini/guide-naming-conventions.html) for artifact id's should be lowercase by default anyways. If the user gives an artifact id with capitals in it then that doesn't technically break the spec, even if it breaks the standard. Due to that I won't modify the artifact id that's given, but I will fix the default package name issue.
