### ISSUE TITLE
IntelliJ Freezes when opening NBT

### ISSUE THREAD

**Issue by izofar** [DemonWav/MinecraftDevIntelliJ#1893]
Reproduce: Try to open [outside_cage.nbt](https://github.com/izofar/takes-a-pillage/blob/04eec5277b0bbcfd086723ba7c2f908774a9b89b/src/main/resources/data/takesapillage/structures/bastille/corner/outside_cage.nbt) with Minecraft Development plugin version `2021.3-1.5.20-348` on Intellij IDEA version `2021.3.3`. I was able to open it with [Minecraft NBT Support v1.5.2](https://github.com/tth05/minecraft-nbt-intellij-plugin), though I prefer being able to do find-and-replace

**Comment by DenWav** [comment]
Thanks, it's supposed to be handled in a separate thread, will look into it.

**Comment by DenWav** [comment]
I'm not sure I can do much more about this. The only parts that are executed on the UI thread are the parts that have to be executed on the UI thread, and they aren't my code. The spots where the IDE freezes when you open a large file are during file parsing (and the creation of the virtual NBTT file that you interact with). Due to IntelliJ's threading rules I am not allowed to do those tasks in the background. I don't know if there's anything I can do to fix it past the attempts I make in e98f08eef9a2ecf49160dbc92f738e24f99d91f5.

**Comment by izofar** [comment]
The latest commit, plus increasing my max heap size to 4092 MiB, seemed to fix it. Thanks
