### ISSUE TITLE
Unable to download versions

### ISSUE THREAD

**Issue by 9965086** [DemonWav/MinecraftDevIntelliJ#2156]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.10

### IntelliJ version

IU-232.10203.10

### Operating System

Windows

### Target platform

Spigot, Paper

### Additional description

![image](https://github.com/minecraft-dev/MinecraftDev/assets/85790323/18d37b26-3c3c-431d-be09-a86292df0ab4)
plugin下的无法获取版本
但是mod的下的却可以

**Comment by YuWan-030** [comment]
我也是遇到了这个问题，不知道怎么解决，有魔法也没用

**Comment by YuWan-030** [comment]
我已经解决了这个问题，并且找到了问题所在：在一些国家，比如中国大陆，由于网络限制的原因，无法直接连接到 Minecraft 服务器版本的下载地址。因此，在IDEA内需要设置内置代理。否则，IDEA会继续采用直连的方式进行连接。在设置完IDEA内置代理后，问题即可完美解决（请注意，代理需要是海外能访问Minecraft Server版本下载地址的VPS，我使用的是新加坡的代理VPS）。

I have resolved this issue and identified the problem: in some countries, such as mainland China, due to network restrictions, it is not possible to directly connect to the Minecraft Server Version download address. Therefore, it is necessary to set up a built-in proxy within IDEA. Otherwise, IDEA will still attempt a direct connection. After configuring the built-in proxy in IDEA, the problem is perfectly solved. (Please note that the proxy should be a VPS accessible from overseas to reach the Minecraft Server Version download address. I used a proxy VPS in Singapore.)

**Comment by 9965086** [comment]
> 我已经解决了这个问题，并且找到了问题所在：在一些国家，比如中国大陆，由于网络限制的原因，无法直接连接到 Minecraft 服务器版本的下载地址。因此，在IDEA内需要设置内置代理。否则，IDEA会继续采用直连的方式进行连接。在设置完IDEA内置代理后，问题即可完美解决（请注意，代理需要是海外能访问Minecraft Server版本下载地址的VPS，我使用的是新加坡的代理VPS）。
> 
> I have resolved this issue and identified the problem: in some countries, such as mainland China, due to network restrictions, it is not possible to directly connect to the Minecraft Server Version download address. Therefore, it is necessary to set up a built-in proxy within IDEA. Otherwise, IDEA will still attempt a direct connection. After configuring the built-in proxy in IDEA, the problem is perfectly solved. (Please note that the proxy should be a VPS accessible from overseas to reach the Minecraft Server Version download address. I used a proxy VPS in Singapore.)
可以发一下你用的内置代理购买链接吗? 谢谢!

Can you send me a purchase link for the built-in agent you use? thank you!

**Comment by YuWan-030** [comment]
> > 我已经解决了这个问题，并且找到了问题所在：在一些国家，比如中国大陆，由于网络限制的原因，无法直接连接到 Minecraft 服务器版本的下载地址。因此，在IDEA内需要设置内置代理。否则，IDEA会继续采用直连的方式进行连接。在设置完IDEA内置代理后，问题即可完美解决（请注意，代理需要是海外能访问Minecraft Server版本下载地址的VPS，我使用的是新加坡的代理VPS）。
> > 我已经解决了这个问题并确定了问题：在某些国家，例如中国大陆，由于网络限制，无法直接连接到Minecraft服务器版本下载地址。因此，有必要在IDEA中设置一个内置代理。否则，IDEA 仍将尝试直接连接。在IDEA中配置内置代理后，问题就完美解决了。（请注意，代理应为可从海外访问的VPS，以到达Minecraft服务器版本下载地址。我在新加坡使用了代理VPS。 可以发一下你用的内置代理购买链接吗？谢谢!
> 
> 你能向我发送你使用的内置代理的购买链接吗？谢谢！

I use a built-in proxy that I set up with a purchased overseas VPS, and it's not from any specific provider. I'm sorry, but I can't help you resolve this issue. Apologies for any inconvenience.

我使用的内置代理是自己购买海外VPS搭建的，并不是在哪里购买的，帮助不了你解决这个问题，非常抱歉。

**Comment by YuWan-030** [comment]
阿里云白嫖的新加坡服务器搭建v2ray，搭建方法可以参考B站博主：https://www.bilibili.com/video/BV1cw411B7V5/

**Comment by DenWav** [comment]
This is a known issue that I've tried to address a few different ways by trying to get the data using different servers and different URLs if they're available. But it's a challenge because I can set up mirrors for the files that I host, but setting up mirrors for third party APIs is more challenging.

**Comment by 9965086** [comment]
已经好了 谢谢!!!!!

**Comment by 1987953471** [comment]
> 阿里云白嫖的新加坡服务器搭建v2ray，搭建方法可以参考B站博主：https://www.bilibili.com/video/BV1cw411B7V5/

您好，我用了一个香港的服务器搭建了V2Ray，但是如何使用这个服务器来设置idea的内置代理我没有找到相关的教程，你发的这个视频已经没了，能教教我怎么操作吗？

**Comment by 1987953471** [comment]
> 阿里云白嫖的新加坡服务器搭建v2ray，搭建方法可以参考B站博主：https://www.bilibili.com/video/BV1cw411B7V5/

求求了，被这个问题搞得实在是绝望，VPN我也有可就是IDEA连不上，怎么找也找不到解决这个问题的法子，难道全世界就我们几个有遇到这问题吗QAQ
