### ISSUE TITLE
Expected method parameters for @Inject are not shown

### ISSUE THREAD

**Issue by Niko-sk2x** [DemonWav/MinecraftDevIntelliJ#277]
It always takes me a while to get inject method arguments right. And MinecraftDev yells at me that it's wrong, **but doesn't tell me what is wrong**. This error couldn't be made any more annoying.

**Comment by DenWav** [comment]
Delete the method parameters and alt-enter and the plugin will automatically fix the parameters. Granted, that quick-fix should always be available, so that's something worth doing. However, making the error message more "useful" would be a bit ridiculous considering how many different ways the param list could possibly be messed up.

**Comment by Niko-sk2x** [comment]
Most of the time everything is right except `CallbackInfo` that I somehow always manage to mess up or forget entirely and then spend 5+ minutes figuring it out. If I don't forget this is possible the next time, I will try what you suggested.

**Comment by Mumfrey** [comment]
In case it helps, the expected args for callback injectors look like the following.

* For target methods with differing arguments, eg. targetting multiple methods using `*` or by specifying multiple target methods:
     * `handlerName(CallbackInfo)`
* For a single target method or for target methods with the same arguments:
     * `handlerName(TargetArg1, TargetArg2, TargetArg3, CallbackInfo)`
* For capturing locals in a method where the entire frame is `IILjava/lang/String;ZFII`:
     * `handlerName(TargetArg1, TargetArg2, TargetArg3, CallbackInfo, int, int, String, bool, float, int, int)`
* For capturing locals in a method where the entire frame is `IILjava/lang/String;ZFII` but capturing only part of the frame:
     * `handlerName(TargetArg1, TargetArg2, TargetArg3, CallbackInfo, int, int)`

The capture locals frame probably can't be validated in any meaningful way, but as you can see, the part before the `CallbackInfo` is always either empty or will match the arguments of the target.

**Comment by Niko-sk2x** [comment]
Looking back at it, I almost always forget to use `CallbackInfoReturnable` (and why does it actually need to be this one even when I don't use this argument at all?). This error could be corrected by MinecraftDev. It's not exactly easy to figure out what you did wrong, when all it tells you is "it's wrong", and you think everything is correct.

**Comment by Mumfrey** [comment]
`CallbackInfoReturnable` is used when the method has a return value which is not `void` and `CallbackInfo` is used for `void` targets. Mixin tells you what you did wrong if you make this mistake with a specific error message for this situation.

**Comment by Niko-sk2x** [comment]
And why can't MinecraftDev show similar message to the one Mixin shows? It would be much more useful.

Minecraft startup is *much* slower than error in IDE. Sometimes it may take at least a few minutes to start Minecraft and get that class to load. And when I run Minecraft, it's one error at a time. So if there are a few things I get wrong, I may need to run Minecraft a few time, which can easily end up in wasting half an hour on issue that should take no more than a minute to fix.

**Comment by DenWav** [comment]
Two things:

1. Again, as I said the action should be available whenever the error is present, this would probably fix this "issue".
2. Because in the IDE I have somewhat limited space for writing error messages. These messages aren't printed in the build log where I'm free to go crazy with the error details like Mixins is, it's more akin to a heads-up display in the middle of your code.

The error message could certainly display more details, I would probably just hijack how IntelliJ already shows parameter mismatches for method calls. However, it's probably not ever going to be as detailed as a Mixin error message.

In the mean-time, however, making the quick fix always available should smooth everything out.

**Comment by RedNesto** [comment]
c98bc7a39b474fcf90363bd159570b252379b8e0 adds a preview for the signature fix, displayed as a code diff.
