### ISSUE TITLE
Cannot run Minecraft with default Liteloader instance

### ISSUE THREAD

**Issue by mrcow75** [DemonWav/MinecraftDevIntelliJ#281]
After installing the plugin and setting up a liteloader instance, it fails to start minecraft.
Keep in mind this is using GradleStart as the run config.
- I have tried the `-Dmixin.env.disableRefMap=true` JVM arguement, same result
- happens on all minecraft versions, even with correct or invalid mappings

[Crash log](https://pastebin.com/raw/kKW2jWyv)

mcVersion=1.10.2
mcpMappings=stable_29

[build.gradle](https://pastebin.com/raw/787RKnTZ)

**Comment by Mumfrey** [comment]
When using a dependency which uses mixins, you have to use the same mappings it was compiled with. In this case `snapshot_20160628`

**Comment by mrcow75** [comment]
Where can you find the correct compiled mapping to version? (for future refrence)

**Comment by Mumfrey** [comment]
You can either find it by looking in the gradle.properties on the relevant git branch or by checking the value under the "dev" key in the [versions.json](http://dl.liteloader.com/versions/versions.json)

**Comment by DenWav** [comment]
Project creation shouldn't allow selecting MCP versions, it should just take whichever version LiteLoader is using. The developer is free to choose a different mapping version after that if they want to. Shouldn't be hard to fix, thanks for the report.

**Comment by Mumfrey** [comment]
Ok so to fix this going forward, I have [added support in Mixin](https://github.com/SpongePowered/Mixin/commit/f1f60c3ee857d591c349db12ced94cf1f620af1a) to actually read and transform the refMap on-the-fly using the current MCP mappings. I have applied this change to the 1.11.2, 1.12 and 1.12.1 development versions of LiteLoader which are leveraging the current Mixin release 0.7.1. I won't be back-porting this to 1.10.2 since I don't support versions that old.

This basically means going forward that you should be able to use any mappings you like in your project.

**Comment by Niko-sk2x** [comment]
This is the exact thing I asked about on IRC once about running Mixin in other mod's dev environment with different mappings. So this should also allow for example running sponge in dev environment of a mod that uses completely different mappings version.

**Comment by Mumfrey** [comment]
Yes indeed, I meant to tag you in the commit actually and I forgot. I was actually trying to fix this in forgegradle by translating the refMaps and then storing them in a temporary location and then coming up with ways to get Mixin to find them at runtime and then was just like...

Screw it, the new way is less efficient than pre-generating the files, by ye gods is it simpler.

**Comment by Niko-sk2x** [comment]
I'm surprised you didn't know about the mappings files being easily accessible from the code. I actually [use it for reflection and back when I used it - my coremod](https://github.com/OpenCubicChunks/CubicChunks/blob/cd85bf6c97e6a98408ae66dea63e049e1cc07fd5/src/main/java/cubicchunks/util/Mappings.java).

**Comment by Mumfrey** [comment]
I did know that, I've been using it [in LiteLoader since February last year](http://develop.liteloader.com/liteloader/LiteLoader/commit/7b01aee76b8296e9725008f37962a0586b0ed129#079cb2ccd5cbd814352fe6309c688732de3e61c4_320_237). What I was saying was that I didn't really want to do it at runtime because it's inefficient, but I settled on doing that anyway in the end since pre-transforming the refmaps was getting messy and overcomplicated.
