### ISSUE TITLE
Methods and classes should "inherit" client-side properties if their parent method or class is client-side

### ISSUE THREAD

**Issue by mezz** [DemonWav/MinecraftDevIntelliJ#286]
Methods and classes should "inherit" client-side properties if their parent method or class is client-side.
For instance, every subclass I make of `Gui.java` should be considered client-side for the purposes of static analysis, without needing to be marked `@SideOnly(Side.CLIENT)`.
Avoiding explicitly marking classes as client-side is good practice for when the sidedness of things is changed by mojang.

**Comment by marvin-roesch** [comment]
While I generally agree that you should not be warned in the context of a side-only class based on inheritance, introducing "sidedness inheritance" to all methods could lead to problems and ambiguities. FML only removes methods explicitly marked `SideOnly`, but it disregards inheritance. So implicitly treating an inherited client-only method from a common class (Block for instance) as annotated could lead to runtime issues. It's only safe to inherit the side-only status when overriding methods from a side-only class.

**Comment by DenWav** [comment]
I talked to a Jetbrains developer about this actually. IntelliJ supports `@NotNull` and `@Nullable` on methods not annotated as such with the "inferred annotation" system. I'm sure you've seen what I'm talking about, it'll put a `@` in the gutter that will tell you that the method was implicitly marked as `@NotNull`, for example. I asked about how I could leverage this system for my sided inspections, and was told there was no API for it. So unfortunately I would basically have to do what they do, but do it all from scratch. I was hoping at some point they would release the API publicly to use, but it doesn't seem like they have any plans on doing so. I haven't checked the latest versions to see if this has been fixed, however, so that is something I need to do.
