### ISSUE TITLE
Integrate with a VCS versioning system.

### ISSUE THREAD

**Issue by 0x277F** [DemonWav/MinecraftDevIntelliJ#29]
Every plugin system in use requires some presence of a versioning system. My suggestion is to allow a VCS commit hash to be used in place of a manually-updated version. I'd recommend a customize-able version string that could have a placeholder for the commit hash (most likely the abridged hash). See https://github.com/spigotmc/scriptus for a bit of clarification on the idea. Note that, as far as I know, Bukkit, Spigot, and BungeeCord plugins would be the only platforms that would allow this, as Forge enforced semver last time I checked. I'd PR this, but I can't be arsed to learn how IntelliJ plugins work.

**Comment by DemonWav** [comment]
Could you or someone else explain to me how you would want to see this implemented? Does this plug-in to the build process somehow? Does it automatically change the code statically whenever it detects a new commit hash? When and how does it go about doing this?

I ask because it seems like if it was implemented on the IDE plugin level, then the project wouldn't be portable from one IDE or environment to another, which would defeat the purpose of using a build system like Maven or Gradle. I could just be seeing it wrong, though, so I just want some clarification on how you would think the implementation would work.

If that is something you (hopefully a plural you all) are actually fine with (a plugin feature that restricts development and collaboration to the project to other people who have the same plugin) then let me know that as well. Lombok is a good example, where without the IDE plugin people can't really contribute to your project. The issue here is, the Lombok plugin's usefulness is quite obvious, while I'm not sure everyone would agree on the usefulness of this feature in this plugin if that's all it provided.

**Comment by 0x277F** [comment]
I definitely see where you're coming from. Considering, in all honesty, I don't actually use this plugin, I don't feel qualified to weigh in on whether people would think it'd be a valuable addition.

**Comment by ryantheleach** [comment]
I think it should use available plugins for either build platform personally, just an option somewhere (or just do it forcefully) to set it up with the initial template.

Even for forge plugins, I'd maybe include the hash in the plugin description or some other variable, that could be accessed for debugging.
