### ISSUE TITLE
Add Gradle support

### ISSUE THREAD

**Issue by gabizou** [DemonWav/MinecraftDevIntelliJ#3]
It would be nice if plugins could be set up with Gradle instead of Maven specifically. I know this is more of speaking from a sponge perspective, but still can use gradle to develop spigot/bukkit plugins just the same.

**Comment by DemonWav** [comment]
Steps needed to add Gradle support:

* Setup the directory structure. This shouldn't require interfacing with the Gradle plugin. This includes whatever build configuration files as well. This will be done in `BuildSystem.create(Project)`.
* Setup the project with the plugin once the project is fully created. This will include telling the Gradle plugin to scan and setup the project as a Gradle project (maybe, this is how Maven does it, may be different for Gradle). This also includes setting up a default run configuration to build the plugin with Gradle. This could also include multiple run configurations if that makes sense to do so. This will be done in `BuildSystem.finishSetup(Project)`.
* Tell Gradle how to import this as our project when it attempts to import the Gradle project (such as when the project is opened, or after we tell the Gradle plugin to scan the project when we first create it). I am hoping this is how we will do it, as that's how the Maven plugin works and it is quite convenient. This will be it's own system, in the `gradle` package under `com.demonwav.mcdev.buildsystem`. Take a look at `com.demonwav.mcdev.buildsystem.maven.*Importer` to get an idea of what I mean. If the Gradle plugin works fundamentally different than this we will need to find some other way to register the project as a Gradle project with it also being our project. I'm sure this can be done because it's an IntelliJ plugin (meaning it should have a nice set of features), and Android also does this. Looking at the Android plugin may give some insight on how to properly do this.

For the first two steps, feel free to look at `com.demonwav.mcdev.buildsystem.maven.MavenBuildSystem` to get an idea of how it was implemented with Maven.

**Comment by DemonWav** [comment]
Initial Gradle detection is working, we should be able to move on to actually implementing this now.

**Comment by DemonWav** [comment]
Implemented as of 64ff71e7
