### ISSUE TITLE
I want use NMS in this plugin

### ISSUE THREAD

**Issue by tomocrafter** [DemonWav/MinecraftDevIntelliJ#322]
Sorry for post in the issues.
but i dont know where can i post like this question, so i did.

i just want use NMS(net.minecraft.server) on this plugin. if i selected spigot or bukkit, its not include nms
how to do this?

**Comment by DenWav** [comment]
Not including support for NMS is quite intentional, if nothing else but to dissuade the usage of NMS in plugins. If you don't know how to use NMS without this plugin automatically setting it up for you (which it never will), then by all accounts that's objectively a good thing, so you won't use NMS at all.

**Comment by Narimm** [comment]
@tomocrafter seriously...I have 5 plugins I have to maintain that use NMS...I  want to die everytime I here a rumour of a new release or minor version...ITS THE DARKSIDE .....and you want to stay away!!!
