### ISSUE TITLE
Plugin cannot get minecraft version.

### ISSUE THREAD

**Issue by EnderBro3D** [DemonWav/MinecraftDevIntelliJ#371]
* Minecraft Development for IntelliJ plugin version: 2017.3-1.2.0
* IntelliJ version: 2017.3.5
* Operating System: Windows 8.1
* Target platform: Spigot

![default](https://user-images.githubusercontent.com/21310836/38311078-1314e18a-3840-11e8-9480-db6d045d5459.png)

**Comment by DenWav** [comment]
This is hosted at https://minecraftdev.org/versions/spigot.json

So it's probably a network issue.

**Comment by EnderBro3D** [comment]
I live in Russian Federation. This website(minecraftdev.org) is blocked in my country =(.
Thanks.

**Comment by DenWav** [comment]
I'll see if I can add some proxies for that which might help.

**Comment by DenWav** [comment]
I've released a new build which should hopefully contain a fix for you. It will fallback to using GitHub as the file provider if the Cloudflare request fails, which should work for you since it seems you have access to GitHub. Let me know if it fixes it, if it doesn't then I'll figure something else out.
