### ISSUE TITLE
About download source

### ISSUE THREAD

**Issue by forestbat** [DemonWav/MinecraftDevIntelliJ#419]
In China，because of the Great FireWall，we have trouble to download resources from their origin address，so I advice you add this：https://lss233.com/artifactory/minecraft to mcdev，and if lag is too long，plugin will change download source。

**Comment by DenWav** [comment]
I'm sorry to hear there's issues with the Maven repos in China (I believe this is what this issue is referring to). I'm not sure how many of my users are in China. If there is an issue though, I'm not going to "fix" it by using an unknown and untrusted mirror.

**Comment by liach** [comment]
@demonwav can you just add a proxy setting?

**Comment by DenWav** [comment]
@liach this is referring to the Maven repo URL in the generated `pom.xml` and `build.gradle` files.

**Comment by Dainsleif233** [comment]
@DenWav Do you plan to add a custom source for the project creation phase to retrieve version information?

**Comment by Strokkur424** [comment]
> Do you plan to add a custom source for the project creation phase to retrieve version information?

It's already possible. You simply have to clone https://github.com/minecraft-dev/templates and you might be able to edit the URL from where it fetches stuff (this is not always available for every version fetch, but some stuff can be edited this way). See: https://mcdev.io/docs/creating-creator-templates/.

This wasn't possible 8 years ago, which is also the reason why this issue was closed. Please do not post on old, long since closed issues in the future.
