### ISSUE TITLE
Code completion attemps to generate a @Shadow for a static method

### ISSUE THREAD

**Issue by Aaron1011** [DemonWav/MinecraftDevIntelliJ#434]
Please include the following information in all issues:

* Minecraft Development for IntelliJ plugin version: `2018.1-1.2.8`
* IntelliJ version: `2018.1.5`
* Operating System: `Linux`
* Target platforms: `Mixin`

When code-completing a method invocation in a Mixin class, MinecraftDev will automatically generate the appropirate `@Shadow` method. However, it attempts to do this even if the method being code-completed is static. Instead of generating a `@Shadow` method, MinecraftDev should generate an import for the owning class.

**Comment by DenWav** [comment]
I'm sure this is just a failure of understanding Mixins on my part, but wouldn't this only be the case for `public static` methods? How are inaccessible `static` methods handled in Mixins, considering you can't define an `abstract static` method to `@Shadow`? Just an empty impl seems like the most reasonable way to handle that, but in that case it's still using a `@Shadow`.

**Comment by gabizou** [comment]
It would make sense that you can still shadow a non-public static modified method.

**Comment by Mumfrey** [comment]
> MinecraftDev should generate an import for the owning class.

Except. and I hate to sound like a broken record here but it's a fundamental property of mixins that everyone seems to forget, **mixins can have multiple targets**.

There is a difference between a `@Shadow` of a method which is a contract which says "a method matching this signature must exist in all targets" and a direct invocation of a `public static` method on a single target.

If you import the target into the Mixin, you are creating a "soft" link between the target *as declared* and the target *at present*. If the mixin target changes in the future (not a completely insane idea given the huge changes we've seen in Minecraft's core over the years) the "soft" link is the developer's responsibility to maintain. Sure it *might* break, and then be obviously in need of change, *but it might not*!

As developers we take responsibility for our decisions and the IDE is a tool which is supposed to help us get the things out of our head and onto the screen as efficiently as possible. There is a huge contractual difference between an `import` and a `@Shadow` and it is up to the **developer** to make that choice.

> Instead of generating a @Shadow method, MinecraftDev should generate an import for the owning class.

No. MCDev's behaviour is the correct one. Auto-completion is a razor-edged balance of doing *enough* for the developer that the tedious parts of coding are eliminated, but not *too much* that the IDE starts to pre-empt decisions made. Normal auto-complete has very straightforward rules which are understood tacitly by the developer, and can be extended at will. Those rules respect scope, and it's perfectly sane that class members can be auto-completed with preference to other foreign members. Inserting the `@Shadow` both respects scope (effectively seamlessly merging the target class scope into the mixin) and preserves the base mixin contract that things in the mixin happen in the context of the targets.

There is **not** equivalence between a `@Shadow` and and static method invocation at a contractual level. And moreover, the the eventual bytecode is the same regardless, so you only **lose** the mixin contract in pursuit of some other stylistic choice.

This is a recurring pattern of thought @Aaron1011 and I encourage you to try and break it. *Just because things are equivalent to you the developer, does not make them equivalent from Mixin's point of view*. This is partly Mixin's fault because it's a powerful way of working with target classes and I would say it's a mark of a good mixin developer to be able to merge your mindspace in this way. It's also MCDev's fault because it's so incredibly good at taking those mental lines and blurring them even further to provide an unparalleled experience for working with mixins.

I would encourage @DemonWav to close this because the current behaviour is the correct one. If the developer wants to invoke a public static method directly then that's up to them. At the very most, it should offer the choice (if possible, not sure what IDEA can actually do) of the `@Shadow` or the `import`.

**Comment by DenWav** [comment]
I'll close this for now based on @Mumfrey's recommendation, if another idea comes out of further discussion then it can be reopened, but after reading @Mumfrey's explanation, I remember again why that behavior is present, and am slightly embarrassed by my original confusion. 😆
