### ISSUE TITLE
Unable to open 1.12.2 PlayerChunkMap class

### ISSUE THREAD

**Issue by Aaron1011** [DemonWav/MinecraftDevIntelliJ#449]
* Minecraft Development for IntelliJ plugin version: `2018.2-1.2.10`
* IntelliJ version: `2018.2.3`
* Operating System: Linux

* Target platforms: Forge/MCP

With MinecraftDev enabled, I'm unable to open the `PlayerChunkMap` class from Forge. No error message appears - the file simply does not open when it's double-clicked. Disabling MinecraftDev allows me to open `PlayerChunkMap` as expected.

**Comment by Aaron1011** [comment]
This continues to be an issue, and is affecting important classes like `Entity`. Currently, I need to disable MinecraftDev whenver I'm not using the debugger in order for Intellij to be useable.

**Comment by liach** [comment]
is there any error in the bottom right corner?

**Comment by Aaron1011** [comment]
Unfortunately, no.

**Comment by gigaherz** [comment]
I have hit the same issue in one of my mod folders. It's not limited to forge classes, I can't even open classes from my mod's packages.

https://streamable.com/xq0uw

Latest non-beta Intellij, latest non-beta MCDev plugin.

I disabled the plugin, and after restarting intellij, it worked, then I reenabled it, and after restarting, it seemed to work at first, but while one of the files was open, I noticed that only some basic level of syntax highlighting was visible, not the full one I normally see. I closed that file and tried to open it again, and it didn't work anymore. Makes me wonder if the bug is blocking/deadlocking the syntax highlighting engine.

If I close and reopen the project, and click on a file fast enough, I can reproduce this behaviour: 
![image](https://user-images.githubusercontent.com/685851/47610535-d7109c00-da57-11e8-8573-6aeeb43d554e.png)

As you can see, the file did open, but it's not fully highlighted.

Edit: To clarify, this only happens in ONE of my mod projects, all the others work just fine. Also, I'm on Windows 10, fully updated, so it's not OS-specific.

**Comment by DenWav** [comment]
Haven't worked on the plugin in a while. Hopefully I can fix this soon.

**Comment by DenWav** [comment]
@Aaron1011 @gigaherz can you confirm this bug is still present? I can't reproduce it on the latest release.
