### ISSUE TITLE
Forge Template 1.13

### ISSUE THREAD

**Issue by Hexeption** [DemonWav/MinecraftDevIntelliJ#571]
The Forge template gonna need to be changed up for the new ForgeGradle 1.13 changes

**Comment by DenWav** [comment]
Yeah, began working on that a while ago. Will happen when it's done.

**Comment by CatRabbit499** [comment]
Just to clarify, this issue is referring to the mention of "genSrgs" in `McpModelBuilderImpl.groovy` correct?
(in Forge-1.13.x / ForgeGradle-3.x, `genSrgs` has been replaced by either `createMcpToSrg` or `extractSrg`)

If so, a check for the FG version could be used to decide which task this line should refer to:
`def mappingFiles = project.tasks.genSrgs.outputs.files.files.collect { it.absolutePath }`

**Comment by DenWav** [comment]
It's very complicated. FG3 is extremely breaking and it's not a simple fix.

**Comment by CatRabbit499** [comment]
What kinds of things are you still working on, and is there anything I can do to help?

**Comment by DenWav** [comment]
This was done a while ago, oops.
