### ISSUE TITLE
Outer Mixin class cannot be referenced from inner Mixin class

### ISSUE THREAD

**Issue by ramidzkh** [DemonWav/MinecraftDevIntelliJ#698]
Suppose the following Mixin
```java
@Mixin(A.class)
public class MixinA {
    @Shadow private int i;

    @Mixin(A.B.class)
    public static class MixinB {
        @Redirect(method = "whatever", at = @At(value = "FIELD", target = "LA;i:I"))
        private int get(A a) {
            return ((MixinA) (Object) a).i + 1; // Here, says Mixin class cannot be referenced directly
        }
    }
}
```

This is completely valid, but the plugin marks the `MixinA` cast in `MixinB` as an error, even though it is valid

**Comment by RedNesto** [comment]
I tried a similar setup with Sponge's Mixin and it fails at runtime (can't cast to the MixinA class), do you use a Mixin fork ?

**Comment by gabizou** [comment]
@Mumfrey could correct me on this, but I do not recall that you can apply mixins and cast to another mixin like this, because at runtime, the other mixin as a class does not exist. You CAN cast other instances of `B` back to this `MixinB` type within `MixinB`, but you cannot cast `A` to `MixinA` within `MixinB` because the contract guarantee that `MixinA`'s transformation is applied.

If however, you're using a fork of SpongePowered's Mixin, then that's on the fork's fault for enabling such a feature that can have bad repercussions for optionally applied Mixins.
