### ISSUE TITLE
Spigot NMS in build.gradle/pom.xml

### ISSUE THREAD

**Issue by ThatGamerBlue** [DemonWav/MinecraftDevIntelliJ#762]
Add a checkbox for NMS support (default unchecked) with a warning that it requires BuildTools to be run, that adds `mavenLocal()` to the dependencies block when using gradle (included by default on maven) and the artifact `group: 'org.spigotmc', name: 'spigot', version: 'spigotVersionGoesHere'`

**Comment by RedNesto** [comment]
I am against adding this option, if someone wants to mess with internals we'd rather let them do that manually, and since it requires running BuildTools this just makes stuff more complicated. This may be the same reason we don't have a Mixin option, you should be able to set it up yourself. Not to mention this only benefits a handful of people and goes beyond the Bukkit/SpigotAPI boundary.

**Comment by ryantheleach** [comment]
I agree with your motivations RedNesto, but I'm somewhat in support of adding it, if a little more then just adding the artifact was involved.

e.g. 
  a small template showing how to either create multiple src sets with multiple version hooks.
  or the classic, creating an abstract class which is instantiated based on the platform version with a pattern in the name.

It would also help to have some sort of mapping support or a way to view the combined sources for Paper/Spigot if there isn't already.

**Motivation:**

As an experienced programmer, creating a reliable and version consistent method of hooking into NMS isn't something that is immediately obvious, (especially given local maven repo's build tools et-all) and aiding people to do it reliably in a way that breaks **cleanly** between versions, instead of running random code that 'looks' like the right method call like half the examples on the net. In addition, dealing with mappings, hooks etc seems to be Minecraft-Devs bread and butter looking at the mixin support for platform development.

MC-Dev is in a unique position at the moment, to promote better practices, at the same time as making it easier for devs to do things the right way.

I understand if this is something that the MC-Dev team doesn't wish to support for **maintenance** reasons, but to reject it based on principal seems somewhat misguided given other badly written guides on the internet that people will use instead.

**Comment by DenWav** [comment]
I have mixed feelings about this. I've declined adding it in the past for principal reasons but @ryantheleach makes a valid point. I think we would need to put some thought into how this actually looks - how would this be implemented? What is the right way to do this? Mixins has a direct API and model which makes supporting it explicitly possible. Something like NMS access, which doesn't have an API at all, is _significantly_ more complex - and to me not clear what that even looks like from this plugin's perspective.

**Comment by DenWav** [comment]
For now I'll label this as declined due to the above discussion. If for nothing else we have a very long list of things we definitely want to support, and here we're not sure if we want to support it at all, so it's probably best to just leave it.

**Comment by Tennessene** [comment]
This is basically what the paperweight-userdev does. You can use it to develop Spigot plugins as long as you use the Spigot API instead of the Paper API. This is what I do anyway. We should draw more attention to #1890
