### ISSUE TITLE
Mixin: add "Fix parameters" option for non-empty injection parameter lists

### ISSUE THREAD

**Issue by nnym** [DemonWav/MinecraftDevIntelliJ#766]
Currently, the "Fix parameters" option in the quick fix list for a Mixin injection appears only when the its parameter list is empty, but it would make more sense and be more convenient if it would appear when the parameter list is not empty so that the parameters do not have to be deleted every time that somebody wants to use the said option.

**Comment by RedNesto** [comment]
Hey ! That's funny because I recently fixed a bug in this inspection and saw a TODO about the same thing
https://github.com/minecraft-dev/MinecraftDev/blob/1fb4aa4e5bff11839985c1e96fc771dc43c91ed8/src/main/kotlin/com/demonwav/mcdev/platform/mixin/inspection/injector/InvalidInjectorMethodSignatureInspection.kt#L105
