### ISSUE TITLE
File generation, intentions, and linting for pack metadata

### ISSUE THREAD

**Issue by ChloeDawn** [DemonWav/MinecraftDevIntelliJ#832]
*This is an elaboration on #198*

```json
{
	"description": "The default data for ProjectName",
	"pack_format": 6
}
```

This file could be auto-generated and include the project name. The pack format could be inferred from the game version target, with an additional code intention for altering this pack version based on a specified game version. There could also be a warning if the pack format mismatches the workspace's target game version.
```
1 for versions 1.6.1 – 1.8.9
2 for versions 1.9 – 1.10.2
3 for versions 1.11 – 1.12.2
4 for versions 1.13 – 1.14.4
5 for versions 1.15 – 1.16.1
6 for versions 1.16.2 – 1.16.5
7 for versions 1.17+
```
*Default description based upon Mojang's own description metadata, encompassing both assets and data*
*Game version associations copied from https://minecraft.gamepedia.com/Tutorials/Creating_a_resource_pack*

**Comment by RedNesto** [comment]
The `pack_format` field is populated with the correct version since 136e12a257c2dd1b503a2baa47dfc1a3226897d0
The inspection is a good idea.
About 1.17, I'm waiting for the forge MDK because the values used are based on it.

**Comment by ChloeDawn** [comment]
What about Fabric?

**Comment by RedNesto** [comment]
I don't know enough about fabric and what file a fabric mod needs.
@Earthcomputer probably knows tho.

**Comment by Earthcomputer** [comment]
Correct me if I'm wrong, but I'm not aware of needing a pack.mcmeta file in Fabric. The one in Forge is in the project creator, and is created with the project.

**Comment by ChloeDawn** [comment]
It's not *required*, but recommended. Iirc fabric still takes the bad approach of generating a pack metadata when it's absent. It should be on the mod to declare their pack format imo

**Comment by ChloeDawn** [comment]
Either way I would appreciate a linter that warns on pack format mismatch

**Comment by jamierocks** [comment]
> Iirc fabric still takes the bad approach of generating a pack metadata when it's absent.

Yes they do. See https://github.com/FabricMC/fabric/blob/9354966b6c119b52108449b5c5f5622c89c5c53e/fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModResourcePackUtil.java#L85-L95 and https://github.com/FabricMC/fabric/blob/9354966b6c119b52108449b5c5f5622c89c5c53e/fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/ModNioResourcePack.java#L86

> It's not required, but recommended.

There's no reference to the file that I could find on their wiki, nor any comments or documentation in code. The functionality in question has existed since the [first commit of fabric-api](https://github.com/FabricMC/fabric/commit/40d55eebefca1c2c9914cb37e34ee9346d4df794#diff-0d63cb96fe2627734b5285a997597528469e1eda26ded085d96b96e872cdbad5R60-R68). So I don't believe that's true.

I'm more than happy to be corrected on this, I haven't been seriously involved with Fabric since its inception - but I have worked with its internals a lot recently for '*fun adventures in running Fabric mods on Forge* '(emphasis on fun).

**Comment by DenWav** [comment]
Seems like to follow the standard an inspection for Forge would be helpful, but the standard practice for Fabric is to not have one.
